# channels:
# - defaults
# dependencies:
# - python=3.6.8
# - scikit-learn=0.21.3
# - pip:
#   - mlflow
#   - cloudpickle==1.2.2
# name: mlflow-env

name: mlfow_tutorial
channels:
  - defaults
dependencies:
  - python=3.8
  - scikit-learn
  - pandas
  - numpy
  - mlflow
  - pip
  - pip:
      - urllib3
